'use client';

import React from 'react';
import Link from 'next/link';
import { BookOpen, Plus, ShieldCheck } from 'lucide-react';

export default function BusinessGlossaryPage() {
  const terms = [
    { term: 'AOV (Average Order Value)', definition: 'Total gross revenue divided by the total number of orders in a given period.', synonyms: 'Order Size, Avg Basket', status: 'Certified', owner: 'Alex Morgan' },
    { term: 'LTV (Lifetime Value)', definition: 'Total historical net revenue generated by a customer account since signup.', synonyms: 'Customer Value, CLV', status: 'Certified', owner: 'Alex Morgan' },
    { term: 'Churn Rate', definition: 'Percentage of active customers who cancelled or did not renew during the last 30 days.', synonyms: 'Attrition Rate', status: 'Certified', owner: 'Sarah Chen' },
    { term: 'RoAS (Return on Ad Spend)', definition: 'Attributed marketing revenue divided by channel ad spend.', synonyms: 'Ad Efficiency', status: 'Verified', owner: 'Alex Morgan' }
  ];

  return (
    <div className="p-4 sm:p-8 max-w-5xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">Business Glossary & Certified Terms</h1>
          <p className="text-xs sm:text-sm text-[#9CA3AF] mt-1">Define certified metric definitions so the AI Analyst strictly uses standardized business logic.</p>
        </div>

        <button className="px-4 py-2 bg-[#D4AF37] hover:bg-[#E5B800] text-black font-bold text-xs rounded-lg flex items-center space-x-2 transition-colors gold-glow">
          <Plus className="w-4 h-4" />
          <span>Define Term</span>
        </button>
      </div>

      {/* Sub-nav */}
      <div className="flex space-x-4 border-b border-[#1A1D24] text-xs font-bold">
        <Link href="/app/settings/profile" className="pb-3 text-[#9CA3AF] hover:text-white">Profile & Role</Link>
        <Link href="/app/settings/glossary" className="pb-3 border-b-2 border-[#D4AF37] text-[#D4AF37]">Business Glossary</Link>
      </div>

      <div className="space-y-4">
        {terms.map((t, idx) => (
          <div key={idx} className="p-5 bg-[#121417] border border-[#1A1D24] rounded-2xl space-y-2 shadow-md">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <BookOpen className="w-4 h-4 text-[#D4AF37]" />
                <h3 className="font-bold text-white text-base">{t.term}</h3>
              </div>
              <span className="px-2.5 py-0.5 rounded text-[11px] font-bold bg-[#D4AF37]/20 text-[#D4AF37] border border-[#D4AF37]/40">
                ✓ {t.status}
              </span>
            </div>

            <p className="text-xs text-gray-200 leading-relaxed">{t.definition}</p>

            <div className="flex items-center justify-between text-[11px] text-[#9CA3AF] pt-2 border-t border-[#1A1D24]">
              <span>Synonyms: {t.synonyms}</span>
              <span>Owner: {t.owner}</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
